#ifndef XM_FFI_H
#define XM_FFI_H

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to an Oxigraph store
 */
typedef struct xm_XmStore xm_XmStore;

/**
 * Open or create an Oxigraph store at the given path.
 *
 * # Safety
 * - `path` must be a valid null-terminated C string
 * - Returns NULL on error
 */
struct xm_XmStore *xm_store_open(const char *path);

/**
 * Open an in-memory Oxigraph store (for testing).
 *
 * # Safety
 * - Returns NULL on error
 */
struct xm_XmStore *xm_store_open_memory(void);

/**
 * Close and free an Oxigraph store.
 *
 * # Safety
 * - `store` must be a valid pointer returned by `xm_store_open*`
 * - After calling, `store` is invalid and must not be used
 */
void xm_store_close(struct xm_XmStore *store);

/**
 * Execute a SPARQL SELECT query and write JSON results to buffer.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `sparql` must be a valid null-terminated SPARQL query
 * - `result_buf` must point to a buffer of at least `buf_len` bytes
 * - Returns number of bytes written, or negative error code
 */
int xm_store_query(struct xm_XmStore *store, const char *sparql, char *result_buf, size_t buf_len);

/**
 * Execute a SPARQL UPDATE (INSERT/DELETE) query.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `sparql` must be a valid null-terminated SPARQL update query
 * - Returns 0 on success, negative error code on failure
 */
int xm_store_update(struct xm_XmStore *store, const char *sparql);

/**
 * Insert a single quad into the store.
 *
 * # Safety
 * - All string parameters must be valid null-terminated C strings
 * - `graph` may be NULL for the default graph
 * - Returns 0 on success, negative error code on failure
 */
int xm_store_insert_quad(struct xm_XmStore *store,
                         const char *subject,
                         const char *predicate,
                         const char *object,
                         const char *graph);

/**
 * Delete a single quad from the store.
 *
 * # Safety
 * - All string parameters must be valid null-terminated C strings
 * - `graph` may be NULL for the default graph
 * - Returns 0 on success, negative error code on failure
 */
int xm_store_delete_quad(struct xm_XmStore *store,
                         const char *subject,
                         const char *predicate,
                         const char *object,
                         const char *graph);

/**
 * Dump a named graph to Turtle format.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `graph` must be a valid graph URI or NULL for default graph
 * - `format` must be one of: "turtle", "ntriples", "nquads"
 * - `buf` must point to a buffer of at least `buf_len` bytes
 * - Returns bytes written, or negative error code
 */
int xm_store_dump_graph(struct xm_XmStore *store,
                        const char *graph,
                        const char *format,
                        char *buf,
                        size_t buf_len);

/**
 * Dump ALL quads from the store (including all named graphs) to N-Quads format.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `buf` must point to a buffer of at least `buf_len` bytes
 * - Returns bytes written, or negative error code
 */
int xm_store_dump_all(struct xm_XmStore *store, char *buf, size_t buf_len);

/**
 * Load RDF data into a named graph.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `graph` must be a valid graph URI or NULL for default graph
 * - `format` must be one of: "turtle", "ntriples", "nquads"
 * - `data` must be a valid null-terminated string of RDF data
 * - Returns 0 on success, negative error code on failure
 */
int xm_store_load_graph(struct xm_XmStore *store,
                        const char *graph,
                        const char *format,
                        const char *data);

/**
 * Get the number of quads in the store.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - Returns count or negative error code
 */
int xm_store_count(struct xm_XmStore *store);

/**
 * Check if the store is empty.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - Returns 1 if empty, 0 if not empty, negative on error
 */
int xm_store_is_empty(struct xm_XmStore *store);

/**
 * List all named graphs in the store, returning JSON array of URIs.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `buf` must point to a buffer of at least `buf_len` bytes
 * - Returns bytes written, or negative error code
 */
int xm_store_list_graphs(struct xm_XmStore *store, char *buf, size_t buf_len);

/**
 * Check if a named graph exists in the store.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `graph` must be a valid null-terminated URI string
 * - Returns 1 if exists, 0 if not, negative on error
 */
int xm_store_graph_exists(struct xm_XmStore *store, const char *graph);

/**
 * Create an empty named graph (inserts graph name into store).
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `graph` must be a valid null-terminated URI string
 * - Returns 0 on success, negative on error
 */
int xm_store_create_graph(struct xm_XmStore *store, const char *graph);

/**
 * Drop a named graph and all its triples.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `graph` must be a valid null-terminated URI string
 * - Returns 0 on success, negative on error
 */
int xm_store_drop_graph(struct xm_XmStore *store, const char *graph);

/**
 * Clear all triples in a named graph (graph name remains).
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `graph` must be a valid null-terminated URI string
 * - Returns 0 on success, negative on error
 */
int xm_store_clear_graph(struct xm_XmStore *store, const char *graph);

/**
 * Count quads in a specific named graph.
 *
 * # Safety
 * - `store` must be a valid store pointer
 * - `graph` must be a valid null-terminated URI string
 * - Returns count, or negative on error
 */
int xm_store_graph_count(struct xm_XmStore *store, const char *graph);

/**
 * Generate a new UUID v4 and write it to the buffer.
 *
 * # Safety
 * - `buf` must point to a buffer of at least 37 bytes (36 chars + null)
 * - Returns number of bytes written (36) or negative error code
 */
int xm_uuid_generate(char *buf, size_t buf_len);

#endif  /* XM_FFI_H */
